spring:
  application:
    name: 92_FITLINK
  datasource:
    url: jdbc:mysql://3.107.192.1:3306/92s_database?createDatabaseIfNotExist=true
    username: springboot
    password: gPwl3977!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false      
    properties:
      hibernate:
        format_sql: true 
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  # Thymeleaf Cache Setting
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      location: ./src/main/resources/static/img/upload/
      max-request-size: 30MB
      max-file-size: 10MB  
    encoding:
      force: true
  security:
    oauth2:
      client:
       registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: 0a72b7ebf2e9f4c8ecbedccc62e08d83
            client-secret: 4Oe7ujoygIDNnBO7FlITIzl3uhgLM9Xn
            scope: profile_nickname, profile_image, account_email
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8088/login/oauth2/code/kakao
            client-name: Kakao
          naver:
            client-id: IPESeR9eKPjxm1I4y83o
            client-secret: jr0eeOsNEP
            scope: name, email, nickname, profile_image, gender, birthday, mobile, birthyear
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8088/login/oauth2/code/naver
          google:
            client-id: 787991624529-e34gkqol0q268q58m8rqgsneivio4rvm.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile


       provider:
           kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-name-attribute: id
            user-info-uri: https://kapi.kakao.com/v2/user/me
            authorization-uri: https://kauth.kakao.com/oauth/authorize
           naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response  
  mail:
    host: smtp.gmail.com
    port: 587
    username: hester0703@gmail.com  
    password: xkpy snhs zbup muhe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
 
kakao:
  rest:
    api:
      key: 0a72b7ebf2e9f4c8ecbedccc62e08d83

# Logging Setting
logging:
  level:
    org:
      hibernate: info

server:
  port: 8088
  servlet:
    encoding:
      force-response: true
      charset: utf-8
#  port: 8443
#  ssl:
#    enabled: true
#    key-store: ./src/main/resources/bootsecurity.p12
#    key-store-password: gPwl3977!
#    key-store-type: PKCS12

#file upload/download
path:
  upload: ./src/main/resources/static/img/upload/
  download: ./src/main/resources/static/img/download/

com:
  lec:
    upload:
      path: ./src/main/resources/static/img/upload/

00Data:
  admin:
    memId: 00Data
    keyString: 76a1a34a775a4e9e80ab69f035c7e7ac

weather:
  api:
    key: a74d20a06c48d4cfefc8e013886b562b
